project:
  type: website

website:
  title: "Data Story"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts.qmd
      - text: About
        href: about.qmd
  page-footer:
    center: "© 2023 Atila Madai"

format:
  html:
    theme: cosmo
